# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.srcs/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/design_1_e203_axi_0_1.xci
# IP: The module: 'design_1_e203_axi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.gen/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.gen/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/src/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.gen/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.gen/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.srcs/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/design_1_e203_axi_0_1.xci
# IP: The module: 'design_1_e203_axi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.gen/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.gen/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/src/clk_wiz_0/clk_wiz_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.gen/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/BaiduSyncdisk/course/Software_Hardware_Co-Design/project/240507_e203_soc/e203_soc.gen/sources_1/bd/design_1/ip/design_1_e203_axi_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc
